name: file_crypt
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  drift: ^2.8.0
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.4
  google_fonts: ^4.0.4
  iconly: ^1.0.1
  path: ^1.8.3
  path_provider: ^2.1.0
  pointycastle: ^3.7.3
  sqlite3_flutter_libs: ^0.5.15

dependency_overrides:
  path: ^1.8.3
  meta: ^1.9.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.8.3
  build_runner: ^2.3.3
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/ic_logo.png"
    background_color: "#406c94"
    theme_color: "#406c94"

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#ff0101"
  fullscreen: false
  image: "assets/splash.jpg"
  android_gravity: fill
  ios_content_mode: scaleToFill
  web_image_mode: cover
